version: '3.8'

services:
  my-postgres:
    image: postgres:15
    container_name: db
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - '5432:5432'
    volumes:
    - pg_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - .:/app/backend
      - static:/app/backend/static
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - my-postgres

  frontend:
    build: ./app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.next
    depends_on:
      - web

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static:/static
    depends_on:
      - frontend

volumes:
  pg_data:
  static:
